### ISSUE TITLE
Scala Anonymous Classes and Subclasses Missing Precise Code Intelligence Reference

### ISSUE THREAD

**Issue by wchau** [sourcegraph/scip-java#414]
`lsif-java` version: `0.7.7`

Type of code: Anonymous Classes and Subclasses

Expected behavior: In Anonymous Classes, use of its fields and methods outside of its class's definition should show up in "Find References". By extension, in Anonymous Subclasses, overridden methods should have abstract / base methods show up in "Find References".

Actual behavior: In Anonymous Classes, use of its fields and methods outside of its class's definition does not show up in "Find References". By extension, in Anonymous Subclasses, overridden methods do not have abstract / base methods show up in "Find References".

```
val a = new {
  val b = 1
}
a.b
```

```
trait A {
  def B(): Unit
}
val a = new A {
  override B(): Unit = {
    print("Hello")
  }
}
```

**Comment by olafurpg** [comment]
I opened a PR to semanticdb-scalac to add support for goto def/ref on structural type members within the same file https://github.com/scalameta/scalameta/pull/2790

I'll close this issue once the next version of semanticdb-scalac is released so that you get a notification.

**Comment by olafurpg** [comment]
Commenting just to confirm that I'm observing expected navigation on Sourcegraph for this issue when using SCIP.
