### ISSUE TITLE
[feature-request] auto-index jdk 17

### ISSUE THREAD

**Issue by ckipp01** [sourcegraph/scip-java#479]
## Problem

We spoke about this briefly on [discord])https://discord.com/channels/969688426372825169/996621621626404995/1005558198259961876), but I wanted to throw this up here to track it as well. Currently if you do an upload using jdk17 for your project you don't have any jdk navigation. You can see an example in [this repo](https://sourcegraph.com/github.com/ckipp01/mill-github-dependency-graph/-/blob/plugin/src/io/kipp/mill/github/dependency/graph/Github.scala). Notice that no navigation for Java sources work in that file.

## Expectation

I'd expect that when my `scip` upload has things like this:

```
symbol: "semanticdb maven jdk 17 java/lang/Object#toString()."
```

That maven jdk17 would be auto-indexed and that code navigation to those jdk sources would work.

**Comment by Strum355** [comment]
Seems to be a problem with how we're querying for JDK on versions above 17 (in the sg instance):
```
> coursier java-home --jvm 17
JVM 17 not found in index: No adopt version matching '1.17+' found
> coursier java-home --jvm 11
/home/noah/.cache/coursier/arc/https/github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%252B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.11_9.tar.gz/jdk-11.0.11+9
```

**Comment by ckipp01** [comment]
> Seems to be a problem with how we're querying for JDK on versions above 17 (in the sg instance):

If you do a `coursier version` what does it show you? If it shows you nothing or that isn't a command, then it's for sure an old coursier issue.

I'd have to look back at the coursier logs, but I'm assuming this had to do with with `adopt` -> `adoptium` change and it now being `temurin`. With the newer coursier versions it should account for this. For example you should see this:

```
❯ cs java-home --jvm 17
/Users/ckipp/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin17-binaries/releases/download/jdk-17%252B35/OpenJDK17-jdk_x64_mac_hotspot_17_35.tar.gz/jdk-17+35/Contents/Home

~/Documents/lua-workspace/nvim-metals debugTests ≡
❯ cs java-home --jvm 11
/Users/ckipp/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.16%252B8/OpenJDK11U-jdk_x64_mac_hotspot_11.0.16_8.tar.gz/jdk-11.0.16+8/Contents/Home
```

**Comment by Strum355** [comment]
Ah that might be it. Would have to bump this in https://github.com/sourcegraph/sourcegraph :eye_speech_bubble:
